pipeline: move gstreamer pipelines into worker processes
hwangsaeul/gaeguli pull request #133
Opened 2021-01-29 11:47 UTC by raghaven447

2021-02-01 14:05 UTC, xhaakon requested changes

2021-02-01 14:05 UTC, xhaakon commented on gaeguli/pipeline.c
> +#ifndef USE_PIPELINE_WORKER_PROCESS
Why remove these?

2021-02-01 14:05 UTC, xhaakon commented on gaeguli/pipeline.c
> +_gaeguli_free_pipeline_worker_args (gchar ** args)
I think you can just use `g_strfreev()`.

2021-02-01 14:05 UTC, xhaakon commented on gaeguli/target.c
> +_gaeguli_free_target_worker_args (gchar ** args)
You can use `g_strfreev()` as long as the last item in the list is NULL.

2021-02-01 14:05 UTC, xhaakon commented on gaeguli/workers/gaeguli-pipeline-worker.c
> +  pipeline_str = g_strdup (argv[1]);
I'd prefer not passing `pipeline_str` as a cmdline argument. Pass only the values necessary to build it and let the child call `_get_enc_string()`.

2021-02-01 14:05 UTC, xhaakon commented on meson.build
> +cdata.set('GAEGULI_TARGET_WORKER_ARGS_NUM', 11)
Why put these two into `meson.build`? Can't they be defined in `gaeguli-internal.h` for instance?

2021-02-04 03:58 UTC, closed without merging

2021-02-04 04:03 UTC, raghaven447 commented
Closing this PR as per the revised changes